<a href="https://colab.research.google.com/github/dongchanlim/CS450/blob/master/MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [51]:
# 28x28 image 60000 instances - train image
# 28x28 image 10000 instances - test image
train_images.shape, test_images.shape 

((60000, 28, 28), (10000, 28, 28))

In [52]:
train_labels, test_labels

(array([5, 0, 4, ..., 5, 6, 8], dtype=uint8),
 array([7, 2, 1, ..., 4, 5, 6], dtype=uint8))

In [53]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

train_images, test_images

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32))

In [0]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [0]:
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(32, activation='relu', input_shape=(784,)))
model.add(layers.Dense(10, activation='softmax'))

In [0]:
model.compile(optimizer='rmsprop',
             loss='categorical_crossentropy',
             metrics=['accuracy'])

In [58]:
model.fit(train_images, train_labels, epochs=5, batch_size = 32)

Epoch 1/5
60000/60000 [==============================] - 2s 36us/step - loss: 0.1504 - accuracy: 0.9572
Epoch 2/5
60000/60000 [==============================] - 2s 35us/step - loss: 0.1361 - accuracy: 0.9606
Epoch 3/5
60000/60000 [==============================] - 2s 35us/step - loss: 0.1252 - accuracy: 0.9641
Epoch 4/5
60000/60000 [==============================] - 2s 35us/step - loss: 0.1166 - accuracy: 0.9668
Epoch 5/5
60000/60000 [==============================] - 2s 35us/step - loss: 0.1098 - accuracy: 0.9682


In [63]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(' test_acc: ', test_acc, "\n", 'test loss: ', test_loss)

10000/10000 [==============================] - 0s 17us/step
 test_acc:  0.9652000069618225 
 test loss:  0.1290582473371178
